version: '2'

services:
  mongo:
    image: mongo:3.6
    container_name: mongo

    networks:
      - frontend_net
      - backend_net
    expose:
      - 27017
    # Notice: bind all IP for develop locally, when deploying it should be deleted!!!
    ports:
      - "27017:27017"

    # Notice: check this user_date volume
    volumes:
      - ../user_data/db:/data/db

networks:
  frontend_net:
    external: true
  backend_net:
    external: true
