version: '3'

services:
  mongo:
    image: mongo:3.6
    container_name: mongo

    networks:
      - frontend_net
      - backend_net
    expose:
      - 27017
    # open public 'ports' for develop, when deploying it should delete!!!
    ports:
      - "27017:27017"

    volumes:
      - ../user_data/db:/data/db

networks:
  frontend_net:
    external: true
  backend_net:
    external: true
